export type ArtifactRef = {
  kind: "RAW_JSON" | "RAW_HTML" | "REPORT_FILE" | "OTHER";
  bucket: string;
  objectKey: string;
  mimeType?: string;
  checksum?: string;
  sizeBytes?: number;
  metadata?: Record<string, unknown>;
};

export type RawSourceEvent = {
  eventId: string;
  runKey: string;
  source: string;
  collectedAt: string;
  url: string;
  payloadVersion: "v1";
  artifacts: ArtifactRef[];
  metadata?: Record<string, unknown>;
  raw: Record<string, unknown>;
};

export type NormalizedSourceEvent = {
  eventId: string;
  runKey: string;
  source: string;
  entityType?: "procurement" | "registry" | "risk_signal" | "company_profile" | "auction";
  payloadVersion: "v1";
  externalId: string;
  title: string;
  description?: string;
  customer?: string;
  supplier?: string;
  supplierInn?: string;
  supplierOgrn?: string;
  organizerName?: string;
  organizerInn?: string;
  messageType?: string;
  shortName?: string;
  kpp?: string;
  amount?: number;
  startPrice?: number;
  currency?: string;
  publishedAt?: string;
  deadlineAt?: string;
  biddingDate?: string;
  eventDate?: string;
  registrationDate?: string;
  decisionDate?: string;
  inclusionDate?: string;
  exclusionDate?: string;
  normalizedAt: string;
  sourceUrl: string;
  status: "ACTIVE" | "CLOSED" | "ARCHIVED" | "DRAFT";
  registryStatus?: string;
  bankruptcyStage?: string;
  caseNumber?: string;
  courtName?: string;
  auctionType?: string;
  lotInfo?: string;
  companyStatus?: string;
  address?: string;
  okved?: string;
  liquidationMark?: boolean;
  legalBasis?: string;
  region?: string;
  riskLevel?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  rawRef?: string;
  sourceSpecificData?: Record<string, unknown>;
  rawEvent: {
    eventId: string;
    runKey: string;
    collectedAt: string;
    url: string;
    artifacts: ArtifactRef[];
  };
};
